### ISSUE TITLE
go1.8.3 panic: The specified procedure could not be found.

### ISSUE THREAD

**Issue by zeropool** [lxn/walk#276] opened 2017-05-25 06:02 UTC
无法启动 windows xp 32 位, 有些系统是没有 uxtheme.dll的 请大大修复

panic: The specified procedure could not be found.

goroutine 1 [running]:
github.com/lxn/win.MustGetProcAddress(0x5adc0000, 0x5c82ef, 0xf, 0x5adc2bef)
        /Users/Zero/env/gopkg/src/github.com/lxn/win/win.go:57 +0x5a
github.com/lxn/win.init.13()
        /Users/Zero/env/gopkg/src/github.com/lxn/win/uxtheme.go:161 +0xa7
github.com/lxn/win.init()
        /Users/Zero/env/gopkg/src/github.com/lxn/win/winspool.go:101 +0x7a
github.com/lxn/walk.init()
        /Users/Zero/env/gopkg/src/github.com/lxn/walk/window.go:1563 +0x43
main.init()
        /Users/Zero/tmp/test/t.go:32 +0x34

**Comment by lxn** [comment] 2017-05-25 07:02
This is a duplicate of https://github.com/lxn/walk/issues/269

**Closed by lxn** 2017-05-25 07:02 UTC
